version: '3'
services:
  redis:
    image: redis
  output:
    build:
      context: ./output
      dockerfile: ./Dockerfile
    image: async_queue/output
    tty: true
    depends_on:
      - redis
  input:
    build:
      context: ./input
      dockerfile: ./Dockerfile
    image: async_queue/input
    ports:
      - 5000:5000
    depends_on:
      - redis
